### ISSUE TITLE
Java Stack Implementation

### ISSUE THREAD

**Issue by riyapandey730** [Anushka-codergirl/Java#82]
Java program to implement stack

**Comment by aashkrish** [comment]
Hey, can you assign this to me?

**Comment by arit950** [comment]
I want to take part

**Comment by aayan14** [comment]
@Anushka-codergirl can you assign me this issue?

**Comment by Anushka-codergirl** [comment]
Okay!

**Comment by aayan14** [comment]
Hey Anushka 

Please check the pull request
